# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-27 02:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0003_auto_20170922_1458'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auctionitem',
            options={'ordering': ['item_number']},
        ),
    ]
