# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-18 17:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0008_auto_20171018_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionitem',
            name='current_bidder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bidding.Bidder'),
        ),
    ]
